version: "3.3"
services:
  redis:
    image: redis

  client:
    image: node:18
    volumes:
      - ./client:/src
    command: /bin/bash -c "cd /src/; npm i; npm run dev"
    ports:
      - 5137:5137

  postgres-db:
    image: postgres
    env_file: envs/db.env
    volumes:
      - pgdata:/var/lib/postgresql/pgdata/
    ports:
      - 5432:5432

  web:
    build: .
    image: edonssfall/imdb
    links:
      - postgres-db:db
      - redis:redis
    volumes:
      - .:/src
      - ./static:/static
    env_file:
      - envs/db.env
      - envs/prod.env

  nginx:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/static:ro
    depends_on:
      - web
    ports:
      - "80:80"

volumes:
  pgdata: {}
  static: {}
