version: "3.3"
services:
  redis:
    image: redis

  postgres-db:
    image: postgres
    env_file: envs/db.env
    volumes:
      - pgdata:/var/lib/postgresql/pgdata/
    ports:
      - 5432:5432

  web:
    build: .
    image: edonssfall/imdb
    links:
      - postgres-db:db
      - redis:redis
    volumes:
      - .:/src
      - ./static:/static
    env_file:
      - envs/db.env
      - envs/prod.env

  nginx:
    image: nginx
    volumes:
      - ./config/nginx-prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/static:ro
      - ./client/dist:/dist:ro
    depends_on:
      - web
    networks:
      - default
      - proxy
    ports:
      - 80:80
    environment:
      - VIRTUAL_HOST=ithillel-leonid.ogir-ok.com
      - LETSENCRYPT_HOST=ithillel-leonid.ogir-ok.com
      - LETSENCRYPT_EMAIL=contact@ithillel-leonid.ogir-ok.com
      - VIRTUAL_PORT=80

volumes:
  pgdata: {}
  static: {}

networks:
  default:
  proxy:
    external: true
