# Generated by Django 4.1.1 on 2022-09-27 11:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(blank=True, max_length=255, verbose_name='IMDB id')),
                ('title_type', models.CharField(choices=[('short', 'Short'), ('movie', 'Movie')], max_length=255, verbose_name='Type of the title')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_adult', models.BooleanField(verbose_name='Is Adult')),
                ('year', models.DateField(null=True, verbose_name='Release Date')),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None, verbose_name='Genres')),
                ('poster_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='url_image')),
                ('rating_imdb', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Rating')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Rank')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(blank=True, max_length=255, verbose_name='IMDB id')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('birth_year', models.DateField(null=True, verbose_name='Birth Year')),
                ('death_year', models.DateField(null=True, verbose_name='Death Year')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='url_image')),
            ],
        ),
        migrations.CreateModel(
            name='PersonMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Ordering')),
                ('job', models.CharField(max_length=255, null=True, verbose_name='Job')),
                ('characters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None, verbose_name='Characters')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie_id', to='imdb.movie')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_id', to='imdb.person')),
            ],
        ),
    ]
