# Generated by Django 4.1 on 2022-10-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Birth Place'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Url Image'),
        ),
    ]
